### ISSUE TITLE
Getting errors when following the document to scale the ASGs

### ISSUE THREAD

**Issue by laxman356** [palantir/bouncer#148]
I'm new to bouncer. I'm following ReadMe document to bounce my ASGs but getting errors doing so. I'm trying to bounce in serial mode
_./bouncer serial -a example-asg:2
INFO[0000] Beginning bouncer serial run
ERRO[0005] ASG desired capacity doesn't match expected starting value  ASG=example-asg desired_capacity actual=1 desired_capacity given=2
FATA[0005] error validating initial ASG state_

Can someone help me with the usage and scale up and down my asg.

**Comment by holtwilkins** [comment]
Hey @laxman356 , this is bouncer's built-in foot-shooting prevention. The short answer is, your ASG's desired capacity is currently set to 1, but on the command-line, you've told bouncer that it should be 2. 

In your case, perhaps a previous run of bouncer failed in the middle, leaving the ASG in a temporary size of 1. The expectation is that you (or terraform) manually increases that back to 2 once the issue that caused bouncer to fail is corrected, then you can watch that the instance comes back healthily, then run bouncer again fresh. Does this make sense?
