### ISSUE TITLE
ECS

### ISSUE THREAD

**Issue by edulop91** [palantir/bouncer#24]
More of a question, but wondering if you've used bouncer with ECS clusters. If so, what's the recommended approach? If not, any interest making bouncer ECS "aware"?

**Comment by holtwilkins** [comment]
I have no experience with ECS, so not sure what making bouncer ECS "aware" would entail, and not sure about describing a recommended approach.  Some work would definitely need to be done here to make this less autoscaling-group-specific most likely.

How similar are the concept for rolling hosts in ECS, as in is there something similar to waiting for hooks to be answered?

**Comment by holtwilkins** [comment]
Going to close this one out for now.
