### ISSUE TITLE
AWS SDK supports AWS_REGION 

### ISSUE THREAD

**Issue by so0k** [palantir/bouncer#30]
currently bouncer aws client is hardcoding the `os.getenv` for `AWS_DEFAULT_REGION` and overwrites region in aws config object - however aws sdk itself supports both `AWS_REGION` and `AWS_DEFAULT_REGION`

this makes bouncer slightly less intuitive to use.. 

The fix for me was to use this null_resource:

```hcl
resource "null_resource" "concourse_worker_bouncer" {
  # A map of arbitrary strings that, when changed, will force the null resource to be replaced, re-running any associated provisioners.
  # Used to trigger based on the evaluation of conditionally gated mutually exclusive launchtemplates
  triggers {
    lc_change = "${element(concat(aws_launch_template.concourse_worker_launchtemplate.*.id, aws_launch_template.concourse_worker_launchtemplate_ephemeral.*.id), 0)}"
  }

  provisioner "local-exec" {
    # Bounce all nodes in this ASG using the canary method
    command = "AWS_DEFAULT_REGION=${var.region} ./bouncerw canary -a '${aws_autoscaling_group.concourse_worker_asg.name}:${var.concourse_worker_instance_count}'"
  }
}
```

**Comment by so0k** [comment]
Will close as this seems to be on purpose as detailed in https://github.com/palantir/bouncer/issues/6

**Comment by holtwilkins** [comment]
Just so I understand @so0k , is the issue that you're setting the environment variable `AWS_REGION`, but not `AWS_DEFAULT_REGION`? Or are you only passing-in a _terraform_ variable `region` into your `aws` provider stanza directly, and not setting either environment variable?

We have some use-cases where we're doing the latter, and we resolved it by wrapping bouncer like this in a terraform module, a similar approach to what you did above.

```
variable "trigger" {
  type = "string"
}

variable "autoscaling_group_spec" {
  type = "string"
}

variable "timeout" {
  default = "20"
}

variable "mode" {
  default = "serial"
}

variable "region" {
  default = ""
}

data "aws_region" "current" {
  name = "${var.region}"
}

resource "null_resource" "bouncer" {
  triggers {
    trigger = "${var.trigger}"
  }

  provisioner "local-exec" {
    command = "bouncer ${var.mode} -t ${var.timeout} -a '${var.autoscaling_group_spec}'"

    environment {
      AWS_DEFAULT_REGION = "${data.aws_region.current.name}"
    }
  }

  lifecycle {
    create_before_destroy = true
  }
}


output "downstream_trigger" {
  value = "${null_resource.bouncer.id}"
}
```

**Comment by so0k** [comment]
the issue was that I initially was passing only `AWS_REGION`

Thank you for showing the HCL to make it more explicit it's an environment variable and I will use similar code to yours as well
