### ISSUE TITLE
Review Required permissions

### ISSUE THREAD

**Issue by so0k** [palantir/bouncer#40]
With Added LaunchTemplate support, the required permissions in [README](https://github.com/palantir/bouncer#required-permissions) would need to be revised

**Comment by so0k** [comment]
At mimimum we need to add `ec2:DescribeLaunchTemplates`

**Comment by holtwilkins** [comment]
Great point. That's the only new API call added, which is here: https://github.com/palantir/bouncer/pull/37/files#diff-de4572d7c0118f08948ab376e48525a3R105 so I think that's it.
