### ISSUE TITLE
use standard env var to specify target region

### ISSUE THREAD

**Issue by dreamlibrarian** [palantir/bouncer#6]
AWS_REGION is not the AWS-standard env var per https://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html; we should switch to AWS_DEFAULT_REGION.

**Comment by holtwilkins** [comment]
The error message did indeed say that, but silently accepted either `AWS_REGION` or `AWS_DEFAULT_REGION`.  I've fixed it and made it stop accepting `AWS_REGION`.

**Comment by dreamlibrarian** [comment]
Weirdly, 0.6.8 actually didn't find things in eu-west-1 when I tried
setting AWS_DEFAULT_REGION; I had to set AWS_REGION. /shrug.
