### ISSUE TITLE
bouncer script not found.

### ISSUE THREAD

**Issue by sanketg86** [palantir/bouncer#63]
Hi Team,
I trying to use bouncer, but something missing here, please let me know, how to fix this.
version: 0.8.7

```
~/bouncer(master)$ ./bouncerw serial --help
Attempting to lock .bouncer_download_lock
Lock acquired
BOUNCER_VERSION is not set. Looking for the latest bouncer release...
Installing bouncer version 0.8.7
tar: bouncer: Cannot open: File exists
tar: Exiting with failure status due to previous errors
Releasing lock on .bouncer_download_lock
Lock released
./bouncerw: line 58: ./bouncer: Is a directory

```

**Comment by holtwilkins** [comment]
Hey @sanketg86 , I'm not totally sure, but it looks like maybe your current directory has some files in it already that are conflicting. Can you make sure you run this from a clean directory that doesn't have an existing file `bouncer.tgz` or `bouncer`?

**Comment by holtwilkins** [comment]
Going to go ahead and close this one out, as it seems like this is probably environment specific to your setup.
