### ISSUE TITLE
Spot fleet support

### ISSUE THREAD

**Issue by Rumbles** [palantir/bouncer#82]
Hi, I was wondering if there is any plan to add support for spot fleets (aws_spot_fleet_request)?

We use a mix of auto scaling groups and spot fleets and it would be great if you could cycle instances in a spot fleet in the same way you can currently with auto scaling groups using bouncer.

Thanks

**Comment by holtwilkins** [comment]
Hey @Rumbles , we have no plans for that right now, no. That said, if you'd like to see about adding support for them, maybe comment back on here on how you'd do so in a way that was modular, given that the code as-written probably makes lots of assumptions about using ASGs explicitly.
